/* generated by lnt2lotos 6.8 */

#ifndef LNT2LOTOS__T__TEST_77_LOBE
#define LNT2LOTOS__T__TEST_77_LOBE

#ifndef CAESAR_ADT_EXPERT_T
#define CAESAR_ADT_EXPERT_T 5.6
#endif

#include "LNT_V1.h"

#include "common.t"

#endif
