#!/bin/sh 
# Script generated with SVL version 2.9

############
# PROLOGUE #
############
. "${SVL:-$CADP}"/src/svl/standard

SVL_DEBUG=""
SVL_SILENT=""
SVL_IGNORE=""

########
# BODY #
########
SVL_PROPERTY_AtLeastOneLassoUnderNoScheduler () {
model="$1"
shift
SVL_PRINT_NEWLINE
SVL_PRINT_MESSAGE \
	"property AtLeastOneLassoUnderNoScheduler (`SVL_QUOTE_PROPERTY_ARG "$model"`)"
SVL_PROPERTY_BEGIN \
	"SOME" \
	"AtLeastOneLassoUnderNoScheduler"
SVL_CHECK_FILE \
	"${model}.bcg"
SVL_RECORD_FOR_SWEEP \
	"svl001_formula_inline"
cat > svl001_formula_inline << SVL_MARKER_END_OF_FORMULA
< true* > < 'EX .*' > @
SVL_MARKER_END_OF_FORMULA
SVL_RECORD_FOR_CLEAN \
	"${model}_one_lasso.bcg"
SVL_VERIFY_INLINE \
	"svl001_formula_inline" \
	"${model}.bcg" \
	"" \
	"${model}_one_lasso.bcg" \
	"$DEFAULT_VERIFY_METHOD" \
	"evaluator4" \
	"7"
SVL_CHECK_EXPECTED_VALUE \
	"TRUE"
SVL_PROPERTY_END
}
SVL_PROPERTY_CanAlwaysReachTermination () {
model="$1"
shift
SVL_PRINT_NEWLINE
SVL_PRINT_MESSAGE \
	"property CanAlwaysReachTermination (`SVL_QUOTE_PROPERTY_ARG "$model"`)"
SVL_PROPERTY_BEGIN \
	"SOME" \
	"CanAlwaysReachTermination"
SVL_CHECK_FILE \
	"${model}.bcg"
SVL_RECORD_FOR_SWEEP \
	"svl002_formula_inline"
cat > svl002_formula_inline << SVL_MARKER_END_OF_FORMULA
[ true* . (not "exit") ] < (not "exit")* . "exit" > true
SVL_MARKER_END_OF_FORMULA
SVL_RECORD_FOR_CLEAN \
	"${model}_no_termination.bcg"
SVL_VERIFY_INLINE \
	"svl002_formula_inline" \
	"${model}.bcg" \
	"" \
	"${model}_no_termination.bcg" \
	"$DEFAULT_VERIFY_METHOD" \
	"evaluator4" \
	"17"
SVL_CHECK_EXPECTED_VALUE \
	"TRUE"
SVL_PROPERTY_END
}
SVL_RECORD_FOR_CLEAN \
	"test_48_none.bcg"
SVL_CHECK_FILE \
	"test_48_none.lnt"
SVL_COMPILE \
	"test_48_none.lnt" \
	"bcg" \
	"" \
	"test_48_none"
SVL_PROPERTY_AtLeastOneLassoUnderNoScheduler \
	"test_48_none"
SVL_PROPERTY_CanAlwaysReachTermination \
	"test_48_none"
SVL_PROPERTY_FreeFromDeadlockLasso () {
model="$1"
shift
SVL_PRINT_NEWLINE
SVL_PRINT_MESSAGE \
	"property FreeFromDeadlockLasso (`SVL_QUOTE_PROPERTY_ARG "$model"`)"
SVL_PROPERTY_COMMENT_OPEN
SVL_PROPERTY_COMMENT_MIDDLE \
	"There are no deadlock lassos in ${model}"
SVL_PROPERTY_COMMENT_CLOSE
SVL_PROPERTY_BEGIN \
	"SOME" \
	"FreeFromDeadlockLasso"
SVL_CHECK_FILE \
	"${model}.bcg"
SVL_RECORD_FOR_SWEEP \
	"svl003_formula_inline"
cat > svl003_formula_inline << SVL_MARKER_END_OF_FORMULA
<true*> (( <  'EX !2 .* !{2}' . true* > @ ) or ( <  'EX !1 .* !{1}' . true* > @ ) or ( <  'EX !1 .* !{1, 2}' . true* . 'EX !2 .* !{1, 2}' . true* > @ ) or ( <  'EX !0 .* !{0}' . true* > @ ) or ( <  'EX !0 .* !{0, 2}' . true* . 'EX !2 .* !{0, 2}' . true* > @ ) or ( <  'EX !0 .* !{0, 1}' . true* . 'EX !1 .* !{0, 1}' . true* > @ ) or ( <  'EX !0 .* !{0, 1, 2}' . true* . 'EX !1 .* !{0, 1, 2}' . true* . 'EX !2 .* !{0, 1, 2}' . true* > @ ))
SVL_MARKER_END_OF_FORMULA
SVL_RECORD_FOR_CLEAN \
	"${model}_deadlock.bcg"
SVL_VERIFY_INLINE \
	"svl003_formula_inline" \
	"${model}.bcg" \
	"" \
	"${model}_deadlock.bcg" \
	"$DEFAULT_VERIFY_METHOD" \
	"evaluator4" \
	"32"
SVL_CHECK_EXPECTED_VALUE \
	"FALSE"
SVL_PROPERTY_END
}
SVL_RECORD_FOR_CLEAN \
	"test_48_obe.bcg"
SVL_CHECK_FILE \
	"test_48_obe.lnt"
SVL_COMPILE \
	"test_48_obe.lnt" \
	"bcg" \
	"" \
	"test_48_obe"
SVL_PROPERTY_FreeFromDeadlockLasso \
	"test_48_obe"
SVL_RECORD_FOR_CLEAN \
	"test_48_hsa.bcg"
SVL_CHECK_FILE \
	"test_48_hsa.lnt"
SVL_COMPILE \
	"test_48_hsa.lnt" \
	"bcg" \
	"" \
	"test_48_hsa"
SVL_PROPERTY_FreeFromDeadlockLasso \
	"test_48_hsa"
SVL_RECORD_FOR_CLEAN \
	"test_48_hsa_obe.bcg"
SVL_CHECK_FILE \
	"test_48_hsa_obe.lnt"
SVL_COMPILE \
	"test_48_hsa_obe.lnt" \
	"bcg" \
	"" \
	"test_48_hsa_obe"
SVL_PROPERTY_FreeFromDeadlockLasso \
	"test_48_hsa_obe"
SVL_RECORD_FOR_CLEAN \
	"test_48_hsa_priority.bcg"
SVL_CHECK_FILE \
	"test_48_hsa_priority.lnt"
SVL_COMPILE \
	"test_48_hsa_priority.lnt" \
	"bcg" \
	"" \
	"test_48_hsa_priority"
SVL_PROPERTY_FreeFromDeadlockLasso \
	"test_48_hsa_priority"
SVL_RECORD_FOR_CLEAN \
	"test_48_lobe.bcg"
SVL_CHECK_FILE \
	"test_48_lobe.lnt"
SVL_COMPILE \
	"test_48_lobe.lnt" \
	"bcg" \
	"" \
	"test_48_lobe"
SVL_PROPERTY_FreeFromDeadlockLasso \
	"test_48_lobe"
SVL_RECORD_FOR_CLEAN \
	"test_48_weak.bcg"
SVL_CHECK_FILE \
	"test_48_weak.lnt"
SVL_COMPILE \
	"test_48_weak.lnt" \
	"bcg" \
	"" \
	"test_48_weak"
SVL_PROPERTY_FreeFromDeadlockLasso \
	"test_48_weak"

############
# EPILOGUE #
############
SVL_PRINT_NEWLINE
SVL_EXIT
