/* generated by lnt2lotos 6.8 */

#ifndef LNT2LOTOS__T__COMMON
#define LNT2LOTOS__T__COMMON

#ifndef CAESAR_ADT_EXPERT_T
#define CAESAR_ADT_EXPERT_T 5.6
#endif

#if ADT_INVALID_NAT (1)
#error "array bound 1 used in type MEMARRAY is out of the domain of type NAT"
#endif

#if ADT_INVALID_NAT (1)
#error "array bound 1 used in type MEMARRAY is out of the domain of type NAT"
#endif

/* ------------------------------------------------------------------------- */

typedef unsigned char ADT_RANGE__MEMLOC;

#ifndef lint
#define CAESAR_ADT_BITS_ADT_RANGE__MEMLOC : 1
#endif

#define CAESAR_ADT_SCALAR_ADT_RANGE__MEMLOC

#define ADT_RANGE_CMP__MEMLOC(ADT_X1,ADT_X2) ((ADT_X1) == (ADT_X2))

#define ADT_RANGE_PRINT__MEMLOC(ADT_FILE,ADT_X) fprintf (ADT_FILE, "%u", (unsigned int) (ADT_X) + 1)

#define ADT_RANGE_ENUM_FIRST__MEMLOC() 0

#define ADT_RANGE_ENUM_NEXT__MEMLOC(CAESAR_ADT_0) (CAESAR_ADT_USE (CAESAR_ADT_0), 0)

#define CAESAR_ADT_ITR_FIRST_MEMLOC ADT_RANGE_ENUM_FIRST__MEMLOC
#define CAESAR_ADT_ITR_NEXT_MEMLOC ADT_RANGE_ENUM_NEXT__MEMLOC

#define ADT_RANGE_CONSTRUCTOR__MEMLOC(ADT_X) ((ADT_RANGE__MEMLOC) ((ADT_X) - 1))

#define CAESAR_ADT_MATCH_ADT_RANGE_CONSTRUCTOR__MEMLOC(ADT_X) 1

#define CAESAR_ADT_GET_1_ADT_RANGE_CONSTRUCTOR__MEMLOC(ADT_X) ((ADT_NAT) ((ADT_X) + 1))

#ifdef __GNUC__
#if (__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ > 2))
#pragma GCC diagnostic ignored "-Wtype-limits"
#endif
#endif

#if ADT_INVALID_NAT (1)
#error "range bound 1 used in type MEMLOC is out of the domain of type NAT"
#endif

#if ADT_INVALID_NAT (1)
#error "range bound 1 used in type MEMLOC is out of the domain of type NAT"
#endif

/* ------------------------------------------------------------------------- */

#endif
