/* generated by lnt2lotos 6.8 */

#ifndef LNT2LOTOS__F__PROD_CONS_HSA_OBE
#define LNT2LOTOS__F__PROD_CONS_HSA_OBE

#ifndef CAESAR_ADT_EXPERT_F
#define CAESAR_ADT_EXPERT_F 5.6
#endif

#define ADT_EXCEPTION__NONE__NAME__UNEXPECTED() ""

#include "common.f"

#endif
